---
title: "Pause for thought - check data"
author: 
  - Zhang Chen^[Department of Experimental Psychology, Ghent University, Zhang.Chen@UGent.be]
date: "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"
output: 
  html_document:
    code_folding: hide
    number_sections: true
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.align = "center")
```

This file contains the R code that I use to check the data when programming the experiment.

```{r load libraries}
# load libraries
library(tidyverse)

theme_set(theme_bw())

```

# Load raw data

```{r load raw data files}
# Participants may refresh the experiment, which will restart the experiment.
# Here I define a function that reads a csv file, and adds a new variable 
# 'attempt' that stands for from which attempt each data row comes from.
# For instance, if a participant re-started the experiment, all data from the 
# second time will be from attempt 2, and so forth.
read_csv_add_attempt <- function(file_name) {
  
  # read the raw data file
  d_tmp <- read_csv(file_name, col_types = cols(.default = col_character()))
  
  # initialize the new variable 'attempt'
  d_tmp$attempt <- 0
  
  # each time when participants restarted the experiment,
  # the header would be written to the file as a row
  # thus, each time when the headers occurred in the file
  # we know that participants have re-started the experiment
  d_tmp <- d_tmp %>%
    mutate(
      attempt_increment = ifelse(subject_ID == "subject_ID", 1, 0),
      attempt = attempt + attempt_increment,
      attempt = cumsum(attempt),
      # the attempt variable starts counting from 0, change it into 1
      attempt = attempt + 1
    ) %>%
    # delete the variable attempt_increment
    select(-attempt_increment) %>%
    # delete the rows that include the header
    filter(subject_ID != 'subject_ID')
  
  return(d_tmp)
  
}


main_file_list <- list.files("../../data/test/",
                             pattern = "PauseForThought_main",
                             full.names = TRUE)

d_main <- main_file_list %>%
  map_dfr(read_csv_add_attempt)
```

# Check data

```{r check data}
ntrials <- d_main %>%
  filter(trial_condition == "experimental") %>%
  count(game1_outcome, delay)

ntrials <- d_main %>%
  filter(trial_condition == "experimental") %>%
  count(game2_NG_amount, game2_G_prob)
```

